### ISSUE TITLE
Compile error on Windows due to conflicting trait implementations for `c_long`/`c_int` and `c_ulong`/`c_uint`

### ISSUE THREAD

**Issue by NSilv** [yvan-sraka/hs-bindgen-types#2]
the `core::ffi::c_*` types are defined as type aliases, and on Windows, because of C conventions, `c_long` and `c_ulong` are defined as `i32` and `u32`, rather than `i64` and `u64`. This means that the following code in lib.rs fails with `"conflicting implementations of trait ReprHs for type {u32, i32}"`:
https://github.com/yvan-sraka/hs-bindgen-types/blob/6ff380546aab61e8a2b0ec14a9208184e17d32db/src/lib.rs#L190-L202

I don't think  it's possible to just `#[cfg(not(windows))]` the offending lines either, as that would mean that specifically on windows `long`s would just become `int`s, or viceversa, and that doesn't sound great

**Comment by yvan-sraka** [comment]
Thanks for the bug report! I try first to reproduce it by adding windows target to CI here https://github.com/yvan-sraka/hs-bindgen-types/pull/4
